config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :ducks, only: %i[index show new create] do
    resources :bookings, only: %i[new create show]
  end
  resources :bookings, only: %i[index destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :duck
  belongs_to :user

  validates :start_date, :end_date, presence: true, availability: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/duck.rb
class Duck < ApplicationRecord
  has_many :bookings, dependent: :destroy
  # belongs_to :user
  has_one_attached :photo

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  # has_many :ducks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    ducks_path
  end

  def after_sign_out_path_for(resource)
    ducks_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :find_booking, only: %i[show destroy]

  def index
    @bookings = Booking.where(user: current_user)
  end

  def show
  end

  def new
    @booking = Booking.new
    @duck = Duck.find(params[:duck_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @duck = Duck.find(params[:duck_id])
    @booking.duck = @duck
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    if @booking.user_id == current_user.id
      @booking.destroy
      redirect_to bookings_path
    else
      redirect_to ducks_path
    end
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/ducks_controller.rb
class DucksController < ApplicationController
  before_action :find_duck, only: [:show]

  def index
    @ducks = Duck.all
  end

  def show
  end

  def new
    @duck = Duck.new
  end

  def create
    @duck = Duck.new(duck_params)
    # @duck.user = current_user
    if @duck.save
      redirect_to duck_path(@duck)
    else
      render :new
    end
  end

  private

  def duck_params
    params.require(:duck).permit(:name, :description, :age, :nationality, :photo)
  end

  def find_duck
    @duck = Duck.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1 class="text-center">My Duckventures!</h1>

<div class="duck-body">
  <% @bookings.each do |booking| %>
    <div class="booked-duck">
      <%= cl_image_tag booking.duck.photo.key %>
      <div class="booked-duck-details">
        <h2><%= link_to booking.duck.name, duck_path(booking.duck_id) %></h2>
        <p><%= booking.duck.description %></p>
      </div>
      <div class="booked-duck-dates">
        <p><em><%= booking.start_date.strftime('%A %B %d, %Y') %></em></p>
        <p class="ampersand"><em>to</em></p>
        <p><em><%= booking.end_date.strftime('%A %B %d, %Y') %></em></p>
      </div>
      <div class="cancel-link">
        <%= link_to "Cancel booking", booking_path(booking.id), method: :delete %>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1 class="text-center">Book a Duck</h1>

<div class="container center_div" style="width: 500px" id='duck-booking-dates' data-unavailable="<%= @duck.unavailable_dates.to_json %>">
  <%= simple_form_for [ @duck, @booking ] do |f| %>
    <div class="p-3">
      <%= f.label :start_date, "Start Date:" %>
      <%= f.date_field :start_date, as: :string, value: f.object.try(:strftime,"%d/%m/%Y"), class: 'form-control' %>
    </div>
    <div class="p-3">
      <%= f.label :end_date, "End Date:" %>
      <%= f.date_field :end_date, as: :string, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %>
    </div>
    <div class="p-3">
      <%= f.submit "Book that Duck!", class: "btn btn-primary" %>
    </div>
<% end %>
</div>

app/views/ducks/index.html.erb
<h1 class="text-center">Duck Buddies</h1>

<div class="text-center">
  <% @ducks.each do |duck| %>
    <div class="card-duck">
      <% if duck.photo.attached? %>
        <%= cl_image_tag duck.photo.key %>
      <% end %>
      <div class="card-infos">
        <div>
          <h2><%= duck.name %></h2>
          <p><%= duck.description %></p>
        </div>
        <div class="card-bottom">
          <h2><%= link_to "More info ", duck_path(duck.id) %></h2>
        </div>
    </div>
  </div>
  <% end %>
</div>

app/views/ducks/new.html.erb
<h1 class="text-center">Pimp a Duck</h1>

<div class="row justify-content-center">
  <%= simple_form_for [ @duck ] do |f| %>
    <%= f.label :name, "Name:" %>
    <div class="p-3" style="width: 500px">
      <%= f.text_field :name %>
    </div>
    <%= f.label :age, "Age:" %>
    <div class="p-3" style="width: 500px">
      <%= f.text_field :age %>
    </div>
    <%= f.label :description, "Description:" %>
    <div class="p-3">
      <%= f.text_area :description, data: { editor: 'markdown' }, rows: 3, style: 'width:500px' %>
    </div>
    <%= f.label :nationality, "Nationality:" %>
    <div class="p-3" style="width: 500px">
      <%= f.text_field :nationality %>
    </div>
    <div class="p-3">
      <%= f.input :photo, as: :file, type: "btn btn-primary" %>
    </div>
    <div class="p-3">
      <%= f.submit "Pimp That Duck!", class: "btn btn-primary" %>
    </div>
<% end %>
</div>

app/views/ducks/show.html.erb
<div class="text-center">
  <%= cl_image_tag @duck.photo.key, class: "text-center avatar-profile-xlarge" %>
</div>


<p class="text-center">
  <strong>Name:</strong>
  <%= @duck.name %>
</p>

<p class="text-center">
  <strong>Nationality:</strong>
  <%= @duck.nationality %>
</p>

<p class="text-center">
  <strong>Age:</strong>
  <%= @duck.age %>
</p>

<p class="text-center">
  <strong>Description:</strong>
  <%= @duck.description %>
</p>

<div class="text-center">
  <%= link_to 'Book this duck', new_duck_booking_path(@duck) %>
</div>
&nbsp;
<div class="text-center">
  <%= link_to 'Back', ducks_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDuckbuddies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bubblegum+Sans&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="duck_image" style="background-image: url(https://res.cloudinary.com/dm37aktki/image/upload/v1644318226/duck-home_bm4dju.png)">
<div style="margin-left: 40px">
  <h1>Welcome to Duck Buddies</h1>
  <h5>Insights are often found by simply describing the problem aloud.<br>
    <i>— Duck, Quack Overflow</i></h5><br>
  <h2><%= link_to "See Our Top Ducks!", ducks_path %></h2>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/ducks", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <div class="links">
            <li class="nav-item" id="pimp-link">
              <%= link_to "Pimp Yo' Duck!", new_duck_path, class: "nav-link" %>
            </li>
            <li class="nav-item active" id="pimp-link">
              <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
            </li>
            <li class="nav-item" id="pimp-link">
              <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: "nav-link" %>
            </li>
          </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create an Account", new_user_registration_path, class: "nav-link", id: "pimp-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>